### ISSUE TITLE
Left-bar minimize failsafe does not work

### ISSUE THREAD

**Issue by dg42xyz** [j4rodm/sn-libra#5]
I noticed that a user is able to hide every application menu, including the Libra Toolkit one, which can essentially make the UI unusable unless they know how to/have access to edit the x_jarodm_libra_application_minimize records or disable the user preference for left_bar_minimize.

In the "Libra Left-bar minimize" business rule, it looks like there is already a failsafe, however this does not work due to the query.  On line 44 in that BR, it has `hideApps.addQuery('sys_id','!=',safetyIDs);` but I think this should be `hideApps.addQuery('application_menu.sys_id','!=',safetyIDs);` instead.

It's probably also worth putting those safety IDs into a system property - I did notice that the second one (148ee80edb27481019ced9595e9619b5) doesn't exist in my PDI.

I'd be happy to fork this project and raise a pull request if you are accepting pull requests.

**Comment by j4rodm** [comment]
DG - Thank you for posting. I'll incorporate this into the next version. I do plan on allowing fork/PR/merge processes, but want to get more familiar with how the code should be stored first (e.g. single update set, exploded into separate xml files..?)
